apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: receiver-githubfiles
  name: receiver-githubfiles
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: receiver-githubfiles
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: receiver-githubfiles
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: receiver-githubfiles-githubtoken
        image: quay.io/galexrt/alertmanager-githubfiles-receiver
        name: receiver
        ports:
        - containerPort: 9959
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /githubfiles-receiver.yaml
          name: config
          readOnly: true
          subPath: githubfiles-receiver.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: githubfiles-receiver.yaml
            path: githubfiles-receiver.yaml
          name: receiver-githubfiles-config
        name: config
