apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: alertmanager-githubfiles-receiver
build:
  artifacts:
  - image: quay.io/galexrt/alertmanager-githubfiles-receiver
    docker:
      dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
